In [7]:
import torch  as torch
import numpy as np

In [6]:
torch.__version__

'1.12.1+cu113'

In [9]:
x = np.array([1,2,3,4,5])
x


array([1, 2, 3, 4, 5])

In [10]:
a = torch.tensor(x)
a

tensor([1, 2, 3, 4, 5])

In [12]:
a.dtype

torch.int64

In [13]:
b = torch.as_tensor(x)
b.dtype

torch.int64

In [15]:
c = torch.from_numpy(x)
c.dtype

torch.int64

In [16]:
torch.tensor(x).dtype

torch.int64

In [17]:
## PyTorch Gradient  (AutoGrad)

In [18]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [20]:
 y = x**3 +3*x**2
 y

tensor(20., grad_fn=<AddBackward0>)

In [21]:
y.backward()

In [22]:
x.grad

tensor(24.)

In [23]:
x1 = torch.tensor([[1.,2.,3,4],[4.,3.,2.,1]] , requires_grad=True)
x1

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]], requires_grad=True)

In [25]:
y1 = 3*x1 + 2
y1

tensor([[ 5.,  8., 11., 14.],
        [14., 11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [27]:
out = y1.mean()
out

tensor(9.5000, grad_fn=<MeanBackward0>)

In [28]:
out.backward()

In [29]:
x1.grad

tensor([[0.3750, 0.3750, 0.3750, 0.3750],
        [0.3750, 0.3750, 0.3750, 0.3750]])